const KEY="ganeshChaturthiTransactions";
let transactions=JSON.parse(localStorage.getItem(KEY)||"[]");
const form=document.getElementById("transactionForm"),typeInput=document.getElementById("type"),amountInput=document.getElementById("amount"),descriptionInput=document.getElementById("description"),body=document.getElementById("transactionBody"),empty=document.getElementById("emptyState");
function money(v){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",minimumFractionDigits:2}).format(v)}
function save(){localStorage.setItem(KEY,JSON.stringify(transactions))}
function summary(){const a=transactions.filter(t=>t.type==="added").reduce((s,t)=>s+t.amount,0),e=transactions.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amount,0);document.getElementById("totalAdded").textContent=money(a);document.getElementById("totalExpense").textContent=money(e);document.getElementById("balance").textContent=money(a-e)}
function esc(v){const d=document.createElement("div");d.textContent=v;return d.innerHTML}
function render(){body.innerHTML="";empty.style.display=transactions.length?"none":"block";[...transactions].reverse().forEach(t=>{const tr=document.createElement("tr"),date=new Date(t.date).toLocaleString("en-IN");tr.innerHTML=`<td>${esc(date)}</td><td>${t.type==="added"?"Money Added":"Expense"}</td><td>${esc(t.description)}</td><td class="${t.type==="added"?"money-added":"money-expense"}">${t.type==="added"?"+":"-"}${money(t.amount)}</td><td><button class="delete-btn" onclick="deleteTransaction('${t.id}')">Delete</button></td>`;body.appendChild(tr)});summary()}
form.addEventListener("submit",e=>{e.preventDefault();const amount=Number(amountInput.value),description=descriptionInput.value.trim();if(!amount||amount<=0||!description){alert("Please enter a valid amount and description.");return}transactions.push({id:Date.now().toString()+Math.random().toString(16).slice(2),type:typeInput.value,amount,description,date:new Date().toISOString()});save();render();form.reset();typeInput.value="added";amountInput.focus()});
window.deleteTransaction=id=>{const item=transactions.find(t=>t.id===id);if(item&&confirm(`Delete "${item.description}"?`)){transactions=transactions.filter(t=>t.id!==id);save();render()}};
document.getElementById("clearBtn").addEventListener("click",()=>{if(!transactions.length)return alert("There are no transactions to clear.");if(confirm("Delete ALL transactions? This cannot be undone.")){transactions=[];save();render()}});
document.getElementById("whatsappBtn").addEventListener("click",()=>{const a=transactions.filter(t=>t.type==="added").reduce((s,t)=>s+t.amount,0),e=transactions.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amount,0),b=a-e;let m=`🙏 Ganesh Chaturthi Fund Summary\n\n💰 Total Money Added: ${money(a)}\n💸 Total Expenses: ${money(e)}\n✅ Available Balance: ${money(b)}\n\n`;if(transactions.length){m+="Transactions:\n";[...transactions].reverse().forEach(t=>m+=`${t.type==="added"?"➕":"➖"} ${t.description}: ${money(t.amount)}\n`)}else m+="No transactions recorded yet.";window.open("https://wa.me/?text="+encodeURIComponent(m),"_blank")});
render();
